CREATE TABLE REGISTRO(
ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(25),
APELLIDO VARCHAR(25),
CORREO VARCHAR(25),
USUARIO VARCHAR(25),
CONTRASEÑA VARCHAR(25)
);

CREATE TABLE CATALOGO(
ID BIGINT UNSIGNED AUTO_INCREMENT,
ID_REGISTRO BIGINT UNSIGNED,
MONBRE_PRODUCTO VARCHAR(25),
NOMBRE_VENDEDOR VARCHAR(25),
MARCA_CLICA VARCHAR(25),
PRECIO FLOAT,
CIUDAD VARCHAR(25),
CONTACTO INTEGER(25),
PRIMARY KEY (id),
FOREIGN KEY (ID_REGISTRO) REFERENCES auth_user (id)
);

CREATE TABLE VENTA(
ID_REFERENCIA_VENTA BIGINT UNSIGNED AUTO_INCREMENT,
ID_CATALOGO BIGINT UNSIGNED,
CIUDAD VARCHAR(25),
MARCA_CICLA VARCHAR(25),
PRECIO FLOAT,
CONTACTO INTEGER(25),
IMAGEN BLOB,
PRIMARY KEY (ID_REFERENCIA_VENTA),
FOREIGN KEY (ID_CATALOGO) REFERENCES CATALOGO (ID)
);




/*REGISTRO
INSERT INTO REGISTRO(NOMBRE,APELLIDO,CORREO,USUARIO,CONTRASEÑA)VALUES('JULIETH','CASTRO','JCASTRO200@MISENA.EDU.CO','JULIETH.CASTRO','123456');


CATALOGO
INSERT INTO CATALOGO(ID_REGISTRO,MONBRE_PRODUCTO,NOMBRE_VENDEDOR,MARCA_CLICA,PRECIO,CIUDAD,CONTACTO)VALUES(1,'BICICLETA OPTIMUS 29 PULGADA','PEDRO PEREZ','OPTIMUS',1500000,'BOGOTA',3015761228);
*/